import { defineConfig, devices } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Ports: honor dev.sh's / the wrapper's exported env (SERVER_PORT / WEB_PORT) when
// present; otherwise pick a free random even/odd pair — the same scheme dev.sh uses
// — so a standalone `npm run test:e2e` never collides with other local services.
function freePortPair(): [string, string] {
  const script =
    "const net=require('net');" +
    "const free=p=>new Promise(r=>{const s=net.createServer();s.once('error',()=>r(false));s.once('listening',()=>s.close(()=>r(true)));s.listen(p,'0.0.0.0');});" +
    "(async()=>{for(let i=0;i<200;i++){const b=10000+2*Math.floor(Math.random()*4999);if(await free(b)&&await free(b+1)){process.stdout.write(b+' '+(b+1));return;}}process.exit(1);})();";
  const [s, w] = execFileSync(process.execPath, ['-e', script]).toString().trim().split(' ');
  return [s, w];
}

function resolvePorts(): [string, string] {
  if (process.env.SERVER_PORT && process.env.WEB_PORT) {
    return [process.env.SERVER_PORT, process.env.WEB_PORT];
  }
  const [s, w] = freePortPair();
  // Stabilize across re-imports (Playwright reloads this config per worker).
  process.env.SERVER_PORT = s;
  process.env.WEB_PORT = w;
  return [s, w];
}

const [SERVER_PORT, WEB_PORT] = resolvePorts();

// Write the proxy table trunk serves the SPA behind, and answer with the name
// of the config file to serve with.
//
// FOR: the client calls THREE same-origin backend paths — `/ws`, and the two
// session mints, `/auth/session` (OIDC) and `/auth/guest` (read-only) — and
// `--proxy-backend` is single-use, so a flag can carry only one of them.
// Proxying `/ws` alone left `POST /auth/guest` with trunk, which answers a POST
// to a path it does not serve with 405. The client reads that as a refused
// mint, so every visitor in every spec landed on the sign-in card and the whole
// read-only surface was unreachable from a test. dev.sh renders exactly this
// table into `Trunk.dev.toml` and serves with `--config`; this is the same
// table with the harness's port in it, and the two must be kept in step.
//
// `/auth/callback` deliberately stays with trunk: it is the SPA landing page
// that finishes a sign-in client-side, not a backend route.
function writeTrunkConfig(): string {
  // Relative to this file, exactly as the `cwd` entries below are — the suite
  // is run from `e2e/`, but nothing here should depend on that.
  const leptosApp = join(dirname(fileURLToPath(import.meta.url)), '..', 'leptos-app');
  const committed = readFileSync(join(leptosApp, 'Trunk.toml'), 'utf8');
  const proxies =
    `\n# Generated by playwright.config.ts (gitignored): proxies with the live backend port.\n` +
    `[[proxy]]\nbackend = "ws://127.0.0.1:${SERVER_PORT}/ws"\nws = true\n\n` +
    `[[proxy]]\nbackend = "http://127.0.0.1:${SERVER_PORT}/auth/session"\n\n` +
    `[[proxy]]\nbackend = "http://127.0.0.1:${SERVER_PORT}/auth/guest"\n`;
  // The port in the name: two concurrent runs randomize ports independently,
  // and a shared filename would let the later run repoint the earlier run's
  // trunk at the wrong backend (silently — trunk is not restarted under
  // `reuseExistingServer`).
  const name = `Trunk.e2e.${WEB_PORT}.toml`;
  const path = join(leptosApp, name);
  const content = committed + proxies;
  // Write only on change: Playwright imports this config once per worker
  // process (a retry spawns a fresh one), trunk's watcher covers the crate
  // directory, and an identical-bytes rewrite still triggers a rebuild whose
  // autoreload would pull the page out from under a running spec.
  let existing: string | undefined;
  try {
    existing = readFileSync(path, 'utf8');
  } catch {
    existing = undefined;
  }
  if (existing !== content) {
    writeFileSync(path, content);
  }
  return name;
}

const TRUNK_CONFIG = writeTrunkConfig();

export default defineConfig({
  testDir: '.',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: 'list',
  use: {
    baseURL: `http://localhost:${WEB_PORT}`,
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: [
    {
      // Hermetic e2e: run the durable node on Sled so no Postgres container is
      // needed, even though the app defaults to Postgres for deployment.
      //
      // COMMUNITY_DATA_DIR gives the node a per-run scratch directory instead
      // of the developer's real `~/.community` — a run must not read rows a
      // dev session left (stale uncached links make the unfurl worker fetch
      // external URLs at boot, server-side, where no browser routing can
      // intercept), must not write into that data, and must be able to run
      // WHILE dev.sh runs (sled holds an exclusive lock per path). NOT a HOME
      // override: cargo resolves its toolchain through HOME, and changing it
      // stops `cargo run` outright. Caveat that is by design: when dev.sh has
      // exported the ports, `reuseExistingServer` attaches to the already
      // -running dev node and this env never applies — that mode deliberately
      // runs the specs against the dev node.
      command: 'cargo run -p community-server --release --no-default-features --features sled',
      cwd: '..',
      port: parseInt(SERVER_PORT),
      env: { SERVER_PORT, COMMUNITY_DATA_DIR: join(tmpdir(), `community-e2e-${SERVER_PORT}`) },
      reuseExistingServer: !process.env.CI,
      timeout: 180000,
    },
    {
      // trunk builds the Leptos app to wasm, serves it on $WEB_PORT, and
      // proxies the backend paths listed in the generated config above, so the
      // client talks to one same-origin URL.
      command: `trunk serve --config ${TRUNK_CONFIG} --address 0.0.0.0 --port ${WEB_PORT}`,
      cwd: '../leptos-app',
      port: parseInt(WEB_PORT),
      reuseExistingServer: !process.env.CI,
      timeout: 180000,
    },
  ],
});
