apiVersion: v1
kind: ServiceAccount
metadata:
  name: community-secret-sync
  namespace: community
  labels:
    app.kubernetes.io/name: community-secret-sync
    app.kubernetes.io/part-of: ankurah-community
