apiVersion: v1
kind: ServiceAccount
metadata:
  name: community-web
  namespace: community
  annotations:
    iam.gke.io/gcp-service-account: community-runtime@synesthetic-1.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: community-web
    app.kubernetes.io/part-of: ankurah-community
